# Homeland by DrgnFireYellow
# https://github.com/DrgnFireYellow/Homeland

# The size of the world border in house worlds
houseSize: 100

# Whether to clear players' inventories when visiting someone else's house
clearInventoryOnVisit: true

# Whether to enable custom block and item functionality outside of house worlds
customFunctionalityInAllWorlds: false


# Whether to enable concrete stairs and/or slabs
# WARNING: May cause lag if enabled
concreteStairsAndSlabs:
  enableStairs: false
  enableSlabs: false
