name: Homeland
version: 1.1.0
main: com.drgnfireyellow.homeland.homeland
description: An attempt at recreating Hypixel housing.
author: DrgnFireYellow
website: https://github.com/DrgnFireYellow
api-version: '1.20'
commands:
  'house':
    description: 'Teleport to your house.'
  'visit':
    description: "Teleport to another player's house."
  'housesetting':
    description: 'Change your house settings.'
  'housetoolbox':
    description: 'Shows a menu to obtain the custom items you can use in your house.'
  'housemenu':
    description: 'Shows a menu to open the house toolbox or go to your house.'