name: Homeland
version: 1.2.1
main: com.drgnfireyellow.homeland.Homeland
description: An attempt at recreating Hypixel housing.
author: DrgnFireYellow
website: https://github.com/DrgnFireYellow
api-version: '1.20'
commands:
  'house':
    description: 'Teleport to your house.'
  'visit':
    description: "Teleport to another player's house."

permissions:
  homeland.*:
    description: "Grants access to all Homeland commands."
    children:
      - homeland.house
      - homeland.visit
      - homeland.house.setting
      - homeland.house.toolbox
      - homeland.house.menu
  homeland.house:
    description: "Grants permission to use the /house command to teleport to the user's house world."
    default: true
  homeland.house.*:
    description: "Grants permission to use all subcommands of the /house command."
    children:
      - homeland.house.setting
      - homeland.house.toolbox
      - homeland.house.menu
  homeland.visit:
    description: "Grants permission to use the /visit command to teleport to other players' house worlds."
    default: true
  homeland.house.setting:
    description: "Grants permission to use the /house setting subcommand to change settings for the user's house."
    default: true
  homeland.house.toolbox:
    description: "Grants permission to use the /house toolbox subcommand to get items added by Homeland."
    default: true
  homeland.house.menu:
    description: "Grants permission to use the /house menu subcommand to open the UI for various Homeland functions."
    default: true